### ISSUE TITLE
add ability for typeahead for subject/object to retrieve data from external sources

### ISSUE THREAD

**Issue by balmas** [fbaumgardt/perseids-annotator#43]
The set of existing annotations won't contain a comprehensive list of all possible subjects and objects for annotations.  

It would be nice to have the flexibility to add additional sources to the typeahead.  For example, it would be great to load a standard abbreviations list for all the texts that would map to the data.perseus.org CTS URI/URNs. Or a list of common place names that map to the Pleaides URI, etc.

The immediate priority I think would be to load all of the possible http://data.perseus.org/people/smiths:* uris so that any person identified by such a URI can be easily retrieved.  (For which to choose, when there are multiple, the user will have to consult the Smith's text to disambiguate.)

**Comment by fbaumgardt** [comment]
I'm thinking we'd want to develop a graph-based format for this with ids and labels. Similar to what i'm doing with SNAP currently, but less ad-hoc. Like so:

`
@prefix rdfs: http://www.w3.org/2000/01/rdf-schema# .
@prefix snap: http://data.snapdrgn.net/ontology/snap# .
@prefix perseids-meta: http://data.perseids.org/meta# .

http://data.snapdrgn.net/ a perseids-meta:namespace;
    perseids-meta:member snap:AllianceWith .

snap:AllianceWith rdfs:label "Has Alliance With" .

`
(Or use e.g. rdfs:isDefinedBy instead of perseids-meta:member.)

And then populate the typeahead with a SPARQL query which may or may not be parameterized. 
Edit: Github loves to eat my brackets. But I think you can figure out the notation.

**Comment by balmas** [comment]
that makes sense
